# Generated by Django 5.1.1 on 2024-09-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_book_website_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('love', 'Love'), ('science', 'Science')], default='No genre', max_length=10, null=True),
        ),
    ]
