# Generated by Django 5.1.1 on 2024-09-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(db_index=True, help_text='введите мэйл', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(editable=False, max_length=100),
        ),
    ]
