# Generated by Django 5.1.1 on 2024-09-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_alter_author_website_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='themes',
            field=models.CharField(default='None', max_length=100, unique_for_date='published_date'),
        ),
    ]
