# Generated by Django 5.1.1 on 2024-09-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_book_themes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='themes',
            new_name='book_presentation',
        ),
    ]
